name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  run-unit-tests:

    runs-on: windows-latest

    env:
      Solution_Name: MyMoney.sln                         
      Test_Project_Path: MyMoney.Tests\MyMoney.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        cache: true
        cache-dependency-path: "**/packages.lock.json"

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application
    - name: Restore
      run: dotnet restore --locked-mode

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
